name: AAAAAA
description: aaa
title: "[aaaaa]: "
labels: ["auto"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contato
      description: How can we get in touch witffffeed more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: nome
    attributes:
      label: Nome
      description: How can we get ffffff more info?
      placeholder: ex.seu nome
    validations:
      required: true  
