# This is a basic workflow to help you get started with Actions

name: Teste Issue

# Controls when the workflow will run
on:
  issues:
    types:
      - closed

  #workflow_dispatch:

jobs:
  
  issue-automation:
    if:  ${{ contains(github.event.issue.labels.*.name, 'auto')  }}
    
    runs-on: ubuntu-latest
    #env: 
      #algo    
   
    steps:
      - uses: actions/checkout@v3
      - name: print hello
        id: hello
        run: echo "hello adele"
      - name: goodbye
        id: bye
        run: echo "bye adele"    
      - name: teste
        id: teste
        run: |
          echo "First output"
          echo "Second output"
      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/teste.yml # optional but recommended

      - name: Print the fields
        run: echo "${PARSER_FIELDS}"
        env:
          PARSER_FIELDS: ${{ steps.issue-parser.outputs.jsonString }}
          
      - name: Check params
        id: check-params
        run:
          if [ "${contact}" == ""]; then
            echo "WARNING= - [] sem contact" >> GITHUB_OUTPUT
            echo  "CONTACT_NAME= meu_contato" >> $GITHUB_OUTPUT
          else
            echo ""WARNING_BODY=- [x] enter the contact Name." >> $GITHUB_OUTPUT
            echo "CONTACT_NAME=${CONTACT}" >> $GITHUB_OUTPUT
        env: 
          CONTACT: ${{ steps.issue-parser.outputs.issueparser_contact }}

      - name: Define Params
        id: params-defined
        run:
          echo "CONTATO= ${{ steps.check-params.outputs.CONTACT_NAME }}" >> $GITHUB_OUTPUT
        env: 
          CONTACT: ${{ steps.check-params.outputs.CONTACT_NAME }}
        
     
