# This is a basic workflow to help you get started with Actions

name: Teste Issue

# Controls when the workflow will run
on:
  issues:
    types:
      - closed

  #workflow_dispatch:

jobs:
  
  issue-automation:
    if:  ${{ contains(github.event.issue.labels.*.name, 'auto')  }}
    
    runs-on: ubuntu-latest
    #env: 
      #algo    
   
    steps:
      - uses: actions/checkout@v3
      - name: print hello
        id: hello
        run: echo "hello adele"
      - name: goodbye
        id: bye
        run: echo "bye adele"    
      - name: teste
        id: teste
        run: |
          echo "First output"
          echo "Second output"
          
      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          issue-body: ${{ github.event.issue.body }}
          template-path: .github/ISSUE_TEMPLATE/teste.yml # optional but recommended

      - name: Print the fields
        run: echo "${PARSER_FIELDS}"
        env:
          PARSER_FIELDS: ${{ steps.issue-parser.outputs.jsonString }}
          
      - name: Check params
        id: check-params
        run:
          echo "CONTATO= ${{ steps.issue-parser.outputs.issueparser_contact }}" >> $GITHUB_OUTPUT
          echo "NOME= ${{ steps.issue-parser.outputs.issueparser_nome }}" >> $GITHUB_OUTPUT
         
        env: 
          CONTACT: ${{ steps.issue-parser.outputs.issueparser_contact }}
          NAME: ${{ steps.issue-parser.outputs.issueparser_nome }}
          #ISSUE_FORM: ${{ steps.issue-parser.outputs.jsonString }}

          
      - name: Define Params
        id: params-defined
        run:
          echo "CONTATO= ${{ steps.check-params.outputs.CONTATO }}" >> $GITHUB_OUTPUT
          echo "NOME= ${{ steps.check-params.outputs.NOME }}" >> $GITHUB_OUTPUT
        env: 
          CONTACT: ${{ steps.check-params.outputs.CONTATO }}
          NAME: ${{ steps.check-params.outputs.NOME }}






          


