# This is a basic workflow to help you get started with Actions

name: Teste Issue

# Controls when the workflow will run
on:
  issues:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  process-issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: print hello
        id: hello
        run: echo "hello adele"
      - name: goodbye
        id: hello
        run: echo "bye adele"    

